media: files
content:
  - name: posts
    label: Posts
    path: app/blog/posts
    type: collection
view:
  fields: [ title, date, published ] # title is the first entry and thus will be set to primary
  sort: [ date, title, published ]
  default:
    search: 'author:Naveen'
    sort: date
    sort: desc